### ISSUE TITLE
URGENT -- Error with field migrations

### ISSUE THREAD

**Issue by edster** [websemantics/builder-extension#11]
Migration Files

```
protected $fields = [
        'title'        => 'anomaly.field_type.text',
        'start'        => [
            "type"   => "anomaly.field_type.datetime",
            "config" => [
                "default_value" => "now",
                "mode"          => "datetime",
                "date_format"   => "j F, Y",
                "year_range"    => "-1:+2",
                "time_format"   => "g:i A",
                "step"          => 15
            ]
        ],
        'end'          => [
            "type"   => "anomaly.field_type.datetime",
            "config" => [
                "default_value" => "now",
                "mode"          => "datetime",
                "date_format"   => "j F, Y",
                "year_range"    => "-1:+2",
                "time_format"   => "g:i A",
                "step"          => 15
            ]
        ],
        'all_day'      => [
            "type"   => "anomaly.field_type.boolean",
            "config" => [
                "default_value" => FALSE,
                "on_color"      => "success",
                "off_color"     => "danger",
                "on_text"       => "YES",
                "off_text"      => "NO"
            ]
        ],
        'content'      => 'anomaly.field_type',
        'more_details' => 'anomaly.field_type.relationship',
        'templatable'  => [
            "type"   => "anomaly.field_type.boolean",
            "config" => [
                "default_value" => FALSE,
                "on_color"      => "success",
                "off_color"     => "danger",
                "on_text"       => "YES",
                "off_text"      => "NO"
            ]
        ],
    ];
```

Stack trace

```
[2016-09-17 18:54:13] local.ERROR: exception 'Exception' with message 'Field type [] not found.' in C:\Sites\module_development\vendor\anomaly\streams-platform\src\Addon\FieldType\FieldTypeBuilder.php:95
Stack trace:
#0 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Field\FieldModel.php(198): Anomaly\Streams\Platform\Addon\FieldType\FieldTypeBuilder->build(Array)
#1 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Assignment\AssignmentModel.php(144): Anomaly\Streams\Platform\Field\FieldModel->getType(false)
#2 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Assignment\AssignmentCollection.php(119): Anomaly\Streams\Platform\Assignment\AssignmentModel->getFieldType()
#3 [internal function]: Anomaly\Streams\Platform\Assignment\AssignmentCollection->Anomaly\Streams\Platform\Assignment\{closure}(Object(Anomaly\Streams\Platform\Assignment\AssignmentModel), 1)
#4 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Support\Arr.php(504): array_filter(Array, Object(Closure), 1)
#5 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Support\Collection.php(282): Illuminate\Support\Arr::where(Array, Object(Closure))
#6 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Assignment\AssignmentCollection.php(123): Illuminate\Support\Collection->filter(Object(Closure))
#7 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Stream\StreamModel.php(433): Anomaly\Streams\Platform\Assignment\AssignmentCollection->dates()
#8 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Entry\Parser\EntryDatesParser.php(30): Anomaly\Streams\Platform\Stream\StreamModel->getDateAssignments()
#9 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Entry\Command\GenerateEntryModel.php(57): Anomaly\Streams\Platform\Entry\Parser\EntryDatesParser->parse(Object(Anomaly\Streams\Platform\Stream\StreamModel))
#10 [internal function]: Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel->handle(Object(Websemantics\BuilderExtension\Filesystem\Filesystem), Object(Anomaly\Streams\Platform\Support\Parser), Object(Anomaly\Streams\Platform\Application\Application))
#11 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#12 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel))
#14 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel))
#15 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel))
#17 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel))
#18 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Entry\EntryUtility.php(27): Anomaly\Streams\Platform\Entry\EntryUtility->dispatch(Object(Anomaly\Streams\Platform\Entry\Command\GenerateEntryModel))
#19 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Stream\Command\CompileStream.php(40): Anomaly\Streams\Platform\Entry\EntryUtility->recompile(Object(Anomaly\Streams\Platform\Stream\StreamModel))
#20 [internal function]: Anomaly\Streams\Platform\Stream\Command\CompileStream->handle(Object(Anomaly\Streams\Platform\Entry\EntryUtility))
#21 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#22 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#23 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Stream\Command\CompileStream))
#24 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Stream\Command\CompileStream))
#25 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Stream\Command\CompileStream))
#27 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Stream\Command\CompileStream))
#28 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Stream\StreamModel.php(191): Anomaly\Streams\Platform\Model\EloquentModel->dispatch(Object(Anomaly\Streams\Platform\Stream\Command\CompileStream))
#29 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Assignment\AssignmentModel.php(433): Anomaly\Streams\Platform\Stream\StreamModel->compile()
#30 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Assignment\AssignmentObserver.php(93): Anomaly\Streams\Platform\Assignment\AssignmentModel->compileStream()
#31 [internal function]: Anomaly\Streams\Platform\Assignment\AssignmentObserver->deleted(Object(Anomaly\Streams\Platform\Assignment\AssignmentModel))
#32 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(349): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\Streams\Platform\Assignment\AssignmentModel))
#34 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#35 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1665): Illuminate\Events\Dispatcher->fire('eloquent.delete...', Object(Anomaly\Streams\Platform\Assignment\AssignmentModel))
#36 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1121): Illuminate\Database\Eloquent\Model->fireModelEvent('deleted', false)
#37 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Model\EloquentRepository.php(188): Illuminate\Database\Eloquent\Model->delete()
#38 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Field\Command\DeleteFieldAssignments.php(41): Anomaly\Streams\Platform\Model\EloquentRepository->delete(Object(Anomaly\Streams\Platform\Assignment\AssignmentModel))
#39 [internal function]: Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments->handle(Object(Anomaly\Streams\Platform\Assignment\AssignmentRepository))
#40 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#41 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#42 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments))
#43 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments))
#44 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments))
#46 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments))
#47 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Field\FieldObserver.php(80): Anomaly\Streams\Platform\Support\Observer->dispatch(Object(Anomaly\Streams\Platform\Field\Command\DeleteFieldAssignments))
#48 [internal function]: Anomaly\Streams\Platform\Field\FieldObserver->deleting(Object(Anomaly\Streams\Platform\Field\FieldModel))
#49 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(349): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\Streams\Platform\Field\FieldModel))
#51 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#52 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(164): Illuminate\Events\Dispatcher->fire('eloquent.deleti...', Object(Anomaly\Streams\Platform\Field\FieldModel), true)
#53 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1665): Illuminate\Events\Dispatcher->until('eloquent.deleti...', Object(Anomaly\Streams\Platform\Field\FieldModel))
#54 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1105): Illuminate\Database\Eloquent\Model->fireModelEvent('deleting')
#55 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Model\EloquentRepository.php(188): Illuminate\Database\Eloquent\Model->delete()
#56 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Database\Migration\Field\FieldMigrator.php(61): Anomaly\Streams\Platform\Model\EloquentRepository->delete(Object(Anomaly\Streams\Platform\Field\FieldModel))
#57 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Database\Migration\Command\Reset.php(44): Anomaly\Streams\Platform\Database\Migration\Field\FieldMigrator->reset(Object(EmangeModuleEventsCreateEventsFields))
#58 [internal function]: Anomaly\Streams\Platform\Database\Migration\Command\Reset->handle(Object(Illuminate\Cache\CacheManager), Object(Anomaly\Streams\Platform\Database\Migration\Field\FieldMigrator), Object(Anomaly\Streams\Platform\Database\Migration\Stream\StreamMigrator), Object(Anomaly\Streams\Platform\Database\Migration\Assignment\AssignmentMigrator))
#59 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#60 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#61 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Database\Migration\Command\Reset))
#62 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Database\Migration\Command\Reset))
#63 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Database\Migration\Command\Reset))
#65 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Database\Migration\Command\Reset))
#66 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Database\Migration\Migrator.php(95): Anomaly\Streams\Platform\Database\Migration\Migrator->dispatch(Object(Anomaly\Streams\Platform\Database\Migration\Command\Reset))
#67 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(254): Anomaly\Streams\Platform\Database\Migration\Migrator->runDown('C:\\Sites\\module...', Object(stdClass), false)
#68 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Database\Migration\Migrator.php(32): Illuminate\Database\Migrations\Migrator->reset(Array, false)
#69 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\ResetCommand.php(69): Anomaly\Streams\Platform\Database\Migration\Migrator->reset(Array, false)
#70 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Database\Migration\Console\ResetCommand.php(34): Illuminate\Database\Console\Migrations\ResetCommand->fire()
#71 [internal function]: Anomaly\Streams\Platform\Database\Migration\Console\ResetCommand->fire()
#72 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#73 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#74 C:\Sites\module_development\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#75 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#76 C:\Sites\module_development\vendor\symfony\console\Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#77 C:\Sites\module_development\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Anomaly\Streams\Platform\Database\Migration\Console\ResetCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#78 C:\Sites\module_development\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#79 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Console\Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#80 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(213): Illuminate\Console\Application->call('migrate:reset', Array)
#81 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Addon\Module\Command\UninstallModule.php(43): Illuminate\Foundation\Console\Kernel->call('migrate:reset', Array)
#82 [internal function]: Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule->handle(Object(Anomaly\Streams\Platform\Console\Kernel), Object(Illuminate\Events\Dispatcher), Object(Anomaly\Streams\Platform\Addon\Module\ModuleRepository))
#83 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#84 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#85 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule))
#86 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule))
#87 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#88 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule))
#89 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule))
#90 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Addon\Module\ModuleManager.php(31): Anomaly\Streams\Platform\Addon\Module\ModuleManager->dispatch(Object(Anomaly\Streams\Platform\Addon\Module\Command\UninstallModule))
#91 C:\Sites\module_development\core\anomaly\addons-module\src\Http\Controller\Admin\AddonsController.php(117): Anomaly\Streams\Platform\Addon\Module\ModuleManager->uninstall(Object(Emange\EventsModule\EventsModule))
#92 [internal function]: Anomaly\AddonsModule\Http\Controller\Admin\AddonsController->uninstall(Object(Anomaly\Streams\Platform\Addon\AddonCollection), Object(Anomaly\Streams\Platform\Addon\Module\ModuleManager), Object(Anomaly\Streams\Platform\Addon\Extension\ExtensionManager), 'emange.module.e...')
#93 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#94 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('uninstall', Array)
#95 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Anomaly\AddonsModule\Http\Controller\Admin\AddonsController), 'uninstall')
#96 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Route.php(144): Illuminate\Routing\Route->runController()
#97 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#98 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Http\Middleware\PoweredBy.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#100 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Http\Middleware\SetLocale.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#103 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 C:\Sites\module_development\vendor\anomaly\streams-platform\src\Http\Middleware\ApplicationReady.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#106 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#107 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#108 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#109 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#110 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#111 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\AuthorizeRoutePermission.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#112 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#113 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#114 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\AuthorizeControlPanel.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#115 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#116 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#117 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\AuthorizeModuleAccess.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#118 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#119 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#120 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\AuthorizeRouteRoles.php(98): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#121 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#122 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#123 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#124 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#125 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#126 C:\Sites\module_development\core\anomaly\users-module\src\Http\Middleware\Authenticate.php(92): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#127 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#128 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#129 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#130 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#131 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#132 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#133 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(267): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#134 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#135 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#136 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#137 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#138 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#139 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#140 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#141 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#142 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#143 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#144 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#145 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#146 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#147 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#148 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#149 C:\Sites\module_development\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#150 C:\Sites\module_development\public\index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#151 {main}  
```

**Comment by websemantics** [comment]
You didn't generate that migration file with the Builder extension `make:stream` command, right? I don't remember getting  `config` handled correctly,

**Comment by websemantics** [comment]
Field,  `'content'      => 'anomaly.field_type',` missing a fully qualified field type name, 
change to `anomaly.field_type.text` and reinstall.
